### ISSUE TITLE
Want to confirm whether the sriov-cni-plugin support bnx2x NIC card

### ISSUE THREAD

**Issue by darcyllingyan** [intel/sriov-cni#128]
Hi,
Now I use bnx2x NIC card to create sriov resource pool, but the POD could NOT use it and always report Non-valid Ethernet address:
![image](https://user-images.githubusercontent.com/35722818/83092391-c874e580-a0cf-11ea-8908-fcf85de5f71b.png)

So I want to confirm whether the plugin support bnx2x NIC card? 

Thanks
Darcy

**Comment by killianmuldoon** [comment]
@darcyllingyan This card has not been tested to my knowledge, but I don't see why it wouldn't work with the cni plugin. The above is a driver error and it looks like there's some issue with the MAC address you're setting. Are you picking an explicit MAC address? Could you please fill out one of our issue templates so we have some basic info about your set up?

**Comment by darcyllingyan** [comment]
Hi @killianmuldoon ,
Thanks very much for the response.
I don't assign VF MAC address directly, suppose the DANM will create MAC address for VFs when the sriov-net is used for POD.
My resourceList is: 
```
{
    "resourceList": [
        {
            "resourceName": "sriov_eno2",
            "selectors": {
                "pfNames": [
                    "eno2"
                ]
            }
        }
    ]
}
```

My allocatable is:
```
[root@~]# kubectl get node node-01  -o json | jq '.status.allocatable'
{
  "cpu": "31",
  "ephemeral-storage": "41153760Ki",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "97663808Ki",
  "k8s.io/sriov_eno2": "4",
  "k8s.io/sriov_eno3": "0",
  "pods": "110"
}
```
The ip link is:
```
[root@ihhps-worker-02 ~]# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
56066: eno1.100@eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f0:92:1c:13:91:90 brd ff:ff:ff:ff:ff:ff
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether f1:92:1c:15:90:90 brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether f1:92:1c:15:90:91 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 1 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 2 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 3 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
```

Create one DanmNet to use:
```
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: sriov-a
spec:
  NetworkID: sriov-a
  NetworkType: sriov
  Options:
    #Change this to the name of a valid SR-IOV Device Pool in your cluster
    device_pool: "k8s.io/sriov_eno2"
    cidr: xxx.xxx.xxx.xxx/16
    allocation_pool:
      start: xxx.xxx.xxx.xxx
      end: xxx.xxx.xxx.xxx
```

When I want to create POD with eth1 to use this sriov-a network, it report the above error.
