### ISSUE TITLE
Abstraction proposal

### ISSUE THREAD

**Issue by martinkennelly** [intel/sriov-cni#133]
# Proposal 1
#### Sample CRD demonstrating new vlan_trunk field
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox/sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",  
  "vlan_trunk": "10,11,20-30,100"
}'
```

#### Standardise vlan trunk input
In order to validate the input for vlan trunking, we must define a standard input format.
The vlan trunk input should conform to the regex expression ```^[0-9]+([,\-][0-9]+)*$```. 

#### Convert into provider friendly format
We will transform user provided ```vlan_trunk``` information into a set of vlan integers which allows providers to easily consume. 

```
type map[int]interface{} trunkedVlans
```

#### New interface for providers
```
type ProviderConfig interface {
  InitVlanTrunkConfig(trunkedVlans map[int]interface{})
  ApplyProviderConfig(conf *sriovtypes.NetConf) error
  RemoveProviderConfig(conf *sriovtypes.NetConf) error
}
```

Each new provider must implement the ```ProviderConfig``` interface.
```InitVlanTrunkConfig()``` would consume ```type map[int]interface{} trunkedVlans``` and transform this data to suit its own specific requirements.
```ApplyProviderConfig()``` would be called during cmdAdd to apply feature(s) for which a provider is responsible for. ```RemoveProviderConfig()``` would be called during cmdDel or during failure of cmdAdd.

#### Additions to NetConf struct
One new field must be added to ```NetConf``` struct - ```VlanTrunk```. ```VlanTrunk```will capture the user input. 

##### Modified NetConf struct
```go
type NetConf struct {
          types.NetConf
          OrigVfState    VfState // Stores the original VF state as it was prior to any operations done during cmdAdd flow
          DPDKMode       bool
          Master         string
          MAC            string
          Vlan           *int   `json:"vlan"`
          VlanQoS        *int   `json:"vlanQoS"`
          DeviceID       string `json:"deviceID"` // PCI address of a VF in valid sysfs format
          VFID           int
          ContIFNames    string // VF names after in the container; used during deletion
          MinTxRate      *int   `json:"min_tx_rate"`          // Mbps, 0 = disable rate limiting
          MaxTxRate      *int   `json:"max_tx_rate"`          // Mbps, 0 = disable rate limiting
          SpoofChk       string `json:"spoofchk,omitempty"`   // on|off
          Trust          string `json:"trust,omitempty"`      // on|off
          LinkState      string `json:"link_state,omitempty"` // auto|enable|disable
          VlanTrunk      string `json:"vlan_trunk,omitempty"` // New field          
          RuntimeConfig  struct {
                  Mac string `json:"mac,omitempty"`
          } `json:"runtimeConfig,omitempty"`
  }
```

**Comment by martinkennelly** [comment]
# Proposal 2
## Implement generic interface for providers

#### Sample CRD demonstrating provider and provider_config fields
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox/sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "spoofchk": "off"
  "provider": "mellanox",
  "provider_config": {
      "vlan_trunk": "10,11,20-30,100",
  }
}'
```

#### New interface for providers
Each new provider must implement the ```ProviderConfig``` interface.
A providers implementation of ```LoadValidateProviderConfig()``` will be responsible for unmarshalling ```provider_config```, validate the configuration and upon successful validation, add this new information to ```NetConf```.
```ApplyProviderConfig()``` would be called during cmdAdd. ```RemoveProviderConfig()``` would be called during cmdDel or during failure of cmdAdd as part of cleanup.
```go
type ProviderConfig interface {
  LoadValidateProviderConfig(bytes []byte) error  
  ApplyProviderConfig(conf *sriovtypes.NetConf) error
  RemoveProviderConfig(conf *sriovtypes.NetConf) error
}
```

## Additions to NetConf struct
We propose to add two new fields to NetConf struct - ```Provider``` and ```ProviderConfig```. 

#### Modified NetConf struct
```go
type NetConf struct {
          types.NetConf
          OrigVfState    VfState // Stores the original VF state as it was prior to any operations done during cmdAdd flow
          DPDKMode       bool
          Master         string
          MAC            string
          Vlan           *int   `json:"vlan"`
          VlanQoS        *int   `json:"vlanQoS"`
          DeviceID       string `json:"deviceID"` // PCI address of a VF in valid sysfs format
          VFID           int
          ContIFNames    string // VF names after in the container; used during deletion
          MinTxRate      *int   `json:"min_tx_rate"`          // Mbps, 0 = disable rate limiting
          MaxTxRate      *int   `json:"max_tx_rate"`          // Mbps, 0 = disable rate limiting
          SpoofChk       string `json:"spoofchk,omitempty"`   // on|off
          Trust          string `json:"trust,omitempty"`      // on|off
          LinkState      string `json:"link_state,omitempty"` // auto|enable|disable
          Provider       string `json:"provider,omitempty"`   // intel|mellanox
          ProviderConfig ProviderConfig
          RuntimeConfig  struct {
                  Mac string `json:"mac,omitempty"`
          } `json:"runtimeConfig,omitempty"`
  }
```

## Provider struct example
Each provider will create a struct which will store the configuration from ```provider_config```. This information will be stored in ```NetConf```.
#### Example of Intel Provider struct
```go
type IntelProviderConf struct {
    ProviderConf struct {
        VlanTrunk string `json:"vlan_trunk,omitempty"`
    } `json:"provider_config"`
}
```
